spring:
  profiles:
    active: h2
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  tomcat:
    max-wait: 20000
    max-active: 50
    max-idle: 20
    min-idle: 15

server:
  port: 8080 

security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 milliseconds

UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data


app:
  cors:
    allowedOrigins: http://localhost:3000
